import Head from 'next/head'
import Image from 'next/image'
import { Navbar , Section1 , Section2 } from '../components'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar/>
      <Section1/>
      <Section2/>
  </div>
  
  )
}
